### ISSUE TITLE
Stop Infinite Swipe

### ISSUE THREAD

**Issue by jobayer** [vejei/CarouselView#1]
I have 3 three items in my adapter. Evereything works fine out of the box. But it is scrolling infinitely. Items never ends. Same items iterate again and again. Once the 3rd item is swipped, 1st item comes again. How to disable this facility?

**Comment by vejei** [comment]
Maybe you have to understand what carousel is exactly.

Check [this](https://getbootstrap.com/docs/4.0/components/carousel/#with-controls) for examples.
